# Generated by Django 3.2.16 on 2022-11-09 07:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование подтипа документа')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(2019)], verbose_name='Год')),
                ('order', models.IntegerField(verbose_name='Номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование специальности')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_identificator', models.CharField(max_length=12, verbose_name='ИИН студента')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Имя студента')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Фамилия студента')),
                ('grade', models.IntegerField(verbose_name='Курс обучения')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.program'),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование типа документа')),
                ('document_sub_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.documentsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='storage', verbose_name='Ссылка на файл')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.documenttype')),
            ],
        ),
    ]
